 "use client";
import{useEffect,useState}from"react";import{useRouter}from"next/navigation";
export default function Dashboard(){const[d,setD]=useState<any>(null);const[err,setErr]=useState("");const router=useRouter();
 async function load(){const r=await fetch("/api/organiser/state",{cache:"no-store"});const x=await r.json().catch(()=>null);if(r.status===401){router.push("/organiser/login");return}if(!r.ok){setErr(x?.error||"Failed");return}setD(x)}
 async function judge(answerId:string,result:string){const r=await fetch("/api/organiser/judge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answerId,result})});if(!r.ok){const x=await r.json().catch(()=>null);setErr(x?.error||"Judgement failed")}await load()}
 async function act(action:string){const r=await fetch("/api/organiser/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});if(!r.ok){const x=await r.json().catch(()=>null);setErr(x?.error||"Action failed")}await load()}
 useEffect(()=>{load();const t=setInterval(load,700);return()=>clearInterval(t)},[]);
 return <main className="shell"><div className="top"><div><div className="tag">NEXOVERSE'26</div><h1>Organiser Dashboard</h1></div><button className="btn" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});router.push("/")}}>Logout</button></div>
 <div className="nav"><a href="/organiser/dashboard">Dashboard</a><a href="/organiser/questions">Questions</a><a href="/organiser/live-game">Live Game</a><a href="/organiser/participants">Participants</a><a href="/organiser/leaderboard">Scoreboard</a></div>
 {err&&<p className="error">{err}</p>}{d?.event&&<div className="grid grid2"><div className="card"><h2>Game</h2><p>Status: <b>{d.event.status}</b></p><p>Round: {d.event.active_round_id||"—"}</p><p>Question: {d.question?.question_text||"No active question"}</p><div className="actions">{["start_game","reveal_question","reveal_logo","open_buzzer","close_buzzer","pause","resume","reopen_buzzer","next_question","end_game"].map(a=><button key={a} className="btn" onClick={()=>act(a)}>{a.replaceAll("_"," ").toUpperCase()}</button>)}</div></div><div className="card"><h2>Participants ({d.participants?.length||0})</h2><table className="table"><tbody>{(d.participants||[]).map((p:any)=><tr key={p.id}><td>{p.name}</td><td>{p.department}</td><td>{p.score}</td></tr>)}</tbody></table></div><div className="card"><h2>Current Buzzes</h2><table className="table"><tbody>{(d.buzzes||[]).map((b:any)=><tr key={b.id}><td>#{b.priority}</td><td>{b.participants?.name}</td><td>{b.participants?.department}</td></tr>)}</tbody></table></div><div className="card"><h2>Submitted Answers</h2><table className="table"><tbody>{(d.answers||[]).map((a:any)=><tr key={a.id}><td>{a.participants?.name}</td><td>{a.answer_text}</td><td>{a.result}</td><td>{a.result==="pending"&&<><button className="btn" onClick={()=>judge(a.id,"correct")}>Correct</button> <button className="btn" onClick={()=>judge(a.id,"wrong")}>Wrong</button></>}</td></tr>)}</tbody></table></div></div>}</main>}
